apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: message-service
  template:
    metadata:
      labels:
        app: message-service
    spec:
      containers:
        - name: message-service
          image: {{ .Values.services.message-service.image }}
          ports:
            - containerPort: {{ .Values.services.message-service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: message-service
spec:
  selector:
    app: message-service
  ports:
    - port: 80
      targetPort: {{ .Values.services.message-service.port }}
