apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace | default "devops25-k8s-gethome" }}
  labels:
    name: {{ .Values.global.namespace | default "devops25-k8s-gethome" }}
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }} 