{{- if .Values.services.routing-service.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: routing-service
  namespace: {{ .Values.global.namespace | default "devops25-k8s-gethome" }}
  labels:
    app: routing-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: routing-service
  template:
    metadata:
      labels:
        app: routing-service
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name | default "gethome-service-account" }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: routing-service
          image: {{ .Values.services.routing-service.image }}
          imagePullPolicy: {{ .Values.services.routing-service.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.services.routing-service.port }}
              name: http
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.services.routing-service.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.services.routing-service.env }}
          env:
            {{- range .Values.services.routing-service.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.services.routing-service.port }}
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.services.routing-service.port }}
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: routing-service
  namespace: {{ .Values.global.namespace | default "devops25-k8s-gethome" }}
  labels:
    app: routing-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ .Values.services.routing-service.service.type }}
  selector:
    app: routing-service
  ports:
    - port: {{ .Values.services.routing-service.service.port }}
      targetPort: {{ .Values.services.routing-service.service.targetPort }}
      protocol: TCP
      name: http
{{- end }}
