{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: gethome-secrets
  namespace: {{ .Values.global.namespace | default "devops25-k8s-gethome" }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }} 