{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "gethome-service-account" }}
  namespace: {{ .Values.global.namespace | default "devops25-k8s-gethome" }}
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }} 