{{- if index .Values.services "usermanagement-service" "enabled" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermanagement-service
  namespace: {{ .Values.global.namespace | default "devops25-k8s-gethome" }}
  labels:
    app: usermanagement-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: usermanagement-service
  template:
    metadata:
      labels:
        app: usermanagement-service
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    spec:
      {{- if .Values.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.serviceAccount.name | default "gethome-service-account" }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: usermanagement-service
          image: {{ index .Values.services "usermanagement-service" "image" }}
          imagePullPolicy: {{ index .Values.services "usermanagement-service" "imagePullPolicy" }}
          ports:
            - containerPort: {{ index .Values.services "usermanagement-service" "port" }}
              name: http
          {{- with .Values.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with index .Values.services "usermanagement-service" "resources" }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if index .Values.services "usermanagement-service" "env" }}
          env:
            {{- range index .Values.services "usermanagement-service" "env" }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ index .Values.services "usermanagement-service" "port" }}
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ index .Values.services "usermanagement-service" "port" }}
            initialDelaySeconds: 30
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: usermanagement-service
  namespace: {{ .Values.global.namespace | default "devops25-k8s-gethome" }}
  labels:
    app: usermanagement-service
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  type: {{ index .Values.services "usermanagement-service" "service" "type" }}
  selector:
    app: usermanagement-service
  ports:
    - port: {{ index .Values.services "usermanagement-service" "service" "port" }}
      targetPort: {{ index .Values.services "usermanagement-service" "service" "targetPort" }}
      protocol: TCP
      name: http
{{- end }} 