# Development environment values
global:
  namespace: devops25-k8s-gethome
  environment: development
  imageRegistry: ""
  imagePullSecrets: []

# Replica count for development
replicaCount: 1

# MongoDB configuration for development
mongo:
  enabled: true
  image: mongo:6
  imagePullPolicy: IfNotPresent
  username: root
  password: devpassword
  database: gethome_dev
  storage:
    size: 5Gi
    storageClass: ""
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 27017

# Ingress configuration for development
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: dev-gethome.local
      paths:
        - path: /
          pathType: Prefix
          service: react-client
        - path: /api/auth
          pathType: Prefix
          service: auth-service
        - path: /api/user
          pathType: Prefix
          service: usermanagement-service
        - path: /api/ai
          pathType: Prefix
          service: ai-service
        - path: /api/emergency
          pathType: Prefix
          service: emergency-service
        - path: /api/routing
          pathType: Prefix
          service: routing-service
  tls:
    - secretName: dev-gethome-tls
      hosts:
        - dev-gethome.local

# Services configuration for development
services:
  # AI Service
  ai-service:
    enabled: true
    image: your-dockerhub/ai-service:dev
    imagePullPolicy: IfNotPresent
    port: 8000
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    env:
      - name: MONGODB_URI
        value: "mongodb://mongo:27017/gethome_dev"
      - name: AI_MODEL_PATH
        value: "/app/models"
      - name: DEBUG
        value: "true"
    service:
      type: ClusterIP
      port: 80
      targetPort: 8000

  # Auth Service
  auth-service:
    enabled: true
    image: your-dockerhub/auth-service:dev
    imagePullPolicy: IfNotPresent
    port: 8080
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "development"
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://mongo:27017/gethome_dev"
      - name: JWT_SECRET
        value: "dev-jwt-secret-change-in-production"
      - name: JWT_EXPIRATION
        value: "86400000"
      - name: LOGGING_LEVEL_ROOT
        value: "DEBUG"
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

  # Emergency Service
  emergency-service:
    enabled: true
    image: your-dockerhub/emergency-service:dev
    imagePullPolicy: IfNotPresent
    port: 8080
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "development"
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://mongo:27017/gethome_dev"
      - name: LOGGING_LEVEL_ROOT
        value: "DEBUG"
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

  # Routing Service
  routing-service:
    enabled: true
    image: your-dockerhub/routing-service:dev
    imagePullPolicy: IfNotPresent
    port: 8080
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "development"
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://mongo:27017/gethome_dev"
      - name: LOGGING_LEVEL_ROOT
        value: "DEBUG"
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

  # User Management Service
  usermanagement-service:
    enabled: true
    image: your-dockerhub/usermanagement-service:dev
    imagePullPolicy: IfNotPresent
    port: 8080
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "development"
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://mongo:27017/gethome_dev"
      - name: AUTH_SERVICE_URL
        value: "http://auth-service:80"
      - name: LOGGING_LEVEL_ROOT
        value: "DEBUG"
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

  # React Client
  react-client:
    enabled: true
    image: your-dockerhub/react-client:dev
    imagePullPolicy: IfNotPresent
    port: 80
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    env:
      - name: REACT_APP_API_BASE_URL
        value: "https://dev-gethome.local/api"
      - name: REACT_APP_AUTH_SERVICE_URL
        value: "https://dev-gethome.local/api/auth"
      - name: REACT_APP_ENVIRONMENT
        value: "development"
    service:
      type: ClusterIP
      port: 80
      targetPort: 80

# ConfigMap for development
configMap:
  enabled: true
  data:
    app.name: "GetHome Dev"
    app.version: "1.0.0-dev"
    app.environment: "development"

# Secrets for development
secrets:
  enabled: true
  data:
    jwt-secret: "dev-jwt-secret-change-in-production"
    mongo-password: "devpassword"
    email-password: "dev-email-password"

# Service Account
serviceAccount:
  enabled: true
  name: gethome-dev-service-account
  annotations: {}

# Pod Security Context (relaxed for development)
podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: false
  runAsUser: 1000

# Container Security Context (relaxed for development)
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false
  runAsUser: 1000
  capabilities:
    drop:
      - ALL

# Pod Disruption Budget (disabled for development)
podDisruptionBudget:
  enabled: false
  minAvailable: 1

# Horizontal Pod Autoscaler (disabled for development)
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80 