# Development environment configuration
global:
  namespace: devops25-k8s-gethome
  environment: development
  imageRegistry: "ghcr.io"
  imagePullSecrets: []

# Replica count for development
replicaCount: 1

# MongoDB configuration for development
mongo:
  enabled: true
  image: mongo:6
  imagePullPolicy: IfNotPresent
  username: root
  password: example
  database: gethome
  storage:
    size: 5Gi
    storageClass: ""
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  service:
    type: ClusterIP
    port: 27017

# Monitoring configuration for development
monitoring:
  enabled: true
  
  # Prometheus configuration
  prometheus:
    enabled: true
    image: prom/prometheus:v2.45.0
    imagePullPolicy: IfNotPresent
    retention: "7d"
    storage:
      size: 10Gi
      storageClass: ""
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

  # Grafana configuration
  grafana:
    enabled: true
    image: grafana/grafana:10.0.0
    imagePullPolicy: IfNotPresent
    adminUser: admin
    adminPassword: admin123
    storage:
      size: 5Gi
      storageClass: ""
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 125m
        memory: 256Mi

  # AlertManager configuration
  alertmanager:
    enabled: false  # Disabled in development

# Ingress configuration for development
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: gethome-dev.local
      paths:
        - path: /
          pathType: Prefix
          service: react-client
        - path: /api/auth
          pathType: Prefix
          service: auth-service
        - path: /api/user
          pathType: Prefix
          service: usermanagement-service
        - path: /api/ai
          pathType: Prefix
          service: ai-service
        - path: /api/message
          pathType: Prefix
          service: message-service
        - path: /api/routing
          pathType: Prefix
          service: routing-service
        - path: /monitoring
          pathType: Prefix
          service: grafana
        - path: /prometheus
          pathType: Prefix
          service: prometheus

# Services configuration for development
services:
  # AI Service
  ai-service:
    enabled: true
    image: ghcr.io/aet-devops25/team-gethome/ai-service:develop
    imagePullPolicy: Always
    port: 8000
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
    env:
      - name: MONGODB_URI
        value: "mongodb://mongo:27017/gethome"
      - name: AI_MODEL_PATH
        value: "/app/models"
      - name: ENABLE_METRICS
        value: "true"
      - name: DEBUG
        value: "true"
    service:
      type: ClusterIP
      port: 80
      targetPort: 8000

  # Auth Service
  auth-service:
    enabled: true
    image: ghcr.io/aet-devops25/team-gethome/auth-service:develop
    imagePullPolicy: Always
    port: 8080
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "development"
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://mongo:27017/gethome"
      - name: JWT_SECRET
        value: "dev-jwt-secret-key"
      - name: JWT_EXPIRATION
        value: "86400000"
      - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: "health,info,prometheus,metrics"
      - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
        value: "true"
      - name: LOGGING_LEVEL_COM_AUTHSERVICE
        value: "DEBUG"
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

  # message Service
  message-service:
    enabled: true
    image: ghcr.io/aet-devops25/team-gethome/message-service:develop
    imagePullPolicy: Always
    port: 8080
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "development"
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://mongo:27017/gethome"
      - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: "health,info,prometheus,metrics"
      - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
        value: "true"
      - name: LOGGING_LEVEL_COM_EXAMPLE_GETHOME
        value: "DEBUG"
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

  # Routing Service
  routing-service:
    enabled: true
    image: ghcr.io/aet-devops25/team-gethome/routing-service:develop
    imagePullPolicy: Always
    port: 8080
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "development"
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://mongo:27017/gethome"
      - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: "health,info,prometheus,metrics"
      - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
        value: "true"
      - name: LOGGING_LEVEL_COM_EXAMPLE_ROUTING
        value: "DEBUG"
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

  # User Management Service
  usermanagement-service:
    enabled: true
    image: ghcr.io/aet-devops25/team-gethome/usermanagement-service:develop
    imagePullPolicy: Always
    port: 8080
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
    env:
      - name: SPRING_PROFILES_ACTIVE
        value: "development"
      - name: SPRING_DATA_MONGODB_URI
        value: "mongodb://mongo:27017/gethome"
      - name: AUTH_SERVICE_URL
        value: "http://auth-service:80"
      - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
        value: "health,info,prometheus,metrics"
      - name: MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED
        value: "true"
      - name: LOGGING_LEVEL_COM_USERMANAGEMENT
        value: "DEBUG"
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080

  # React Client
  react-client:
    enabled: true
    image: ghcr.io/aet-devops25/team-gethome/react-client:develop
    imagePullPolicy: Always
    port: 80
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 125m
        memory: 128Mi
    env:
      - name: REACT_APP_API_BASE_URL
        value: "http://gethome-dev.local/api"
      - name: REACT_APP_AUTH_SERVICE_URL
        value: "http://gethome-dev.local/api/auth"
      - name: REACT_APP_ENVIRONMENT
        value: "development"
    service:
      type: ClusterIP
      port: 80
      targetPort: 80

# ConfigMap for development
configMap:
  enabled: true
  data:
    app.name: "GetHome"
    app.version: "1.0.0"
    app.environment: "development"

# Secrets for development
secrets:
  enabled: true
  data:
    jwt-secret: "dev-jwt-secret-key"
    mongo-password: "example"
    email-password: "dev-email-password"

# Service Account
serviceAccount:
  enabled: true
  name: gethome-service-account
  annotations: {}

# Pod Security Context (relaxed for development)
podSecurityContext:
  fsGroup: 1000

# Container Security Context (relaxed for development)
containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  runAsNonRoot: false

# Pod Disruption Budget (disabled in development)
podDisruptionBudget:
  enabled: false

# Horizontal Pod Autoscaler (disabled in development)
hpa:
  enabled: false 