services:
  react-client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - ai-service
      - emergency-service

  emergency-service:
    build: ./service/emergency-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - mongo

  ai-service:
    build: ./service/ai-service
    ports:
      - "8082:80"
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
