services:
  react-client:
    build: ./client
    ports:
      - "3000:80"
    depends_on:
      - ai-service
      - message-service
    environment:
      - REACT_APP_API_BASE_URL=${FRONTEND_URL:-http://localhost:3000}
      - REACT_APP_AUTH_SERVICE_URL=${SERVICE_AUTH_URL:-http://localhost:8081}

  message-service:
    build: ./server/message-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-development}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
    depends_on:
      - mongo

  auth-service:
    build: ./server/auth-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-development}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
    depends_on:
      - mongo

  routing-service:
    build: ./server/routing-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-development}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - OPENROUTE_API_URL=${OPENROUTE_API_URL:-https://api.openrouteservice.org/v2}
      - OPENROUTE_API_KEY=${OPENROUTE_API_KEY}
    depends_on:
      - mongo

  usermanagement-service:
    build: ./server/usermanagement-service
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-development}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-86400000}
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    depends_on:
      - mongo

  ai-service:
    build: ./server/ai-service
    ports:
      - "8085:80"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USER_SERVICE_URL=${SERVICE_USERMANAGEMENT_URL:-http://usermanagement-service:8080}/api/users/{user_id}/profile
    depends_on:
      - mongo

  # Monitoring Stack
  prometheus:
    image: prom/prometheus:v2.40.0
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    depends_on:
      - gethome-metrics-exporter

  grafana:
    image: grafana/grafana:9.3.0
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager:v0.24.0
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'

  gethome-metrics-exporter:
    build: ./server/gethome-metrics-exporter
    ports:
      - "8090:8090"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - AUTH_SERVICE_URL=http://auth-service:8080
      - ROUTING_SERVICE_URL=http://routing-service:8080
      - MESSAGE_SERVICE_URL=http://message-service:8080
      - USER_SERVICE_URL=http://usermanagement-service:8080
      - SCRAPE_INTERVAL=30
      - METRICS_PORT=8090
      - ENVIRONMENT=development
      - DATABASE_TYPE=mongodb
    depends_on:
      - mongo
      - auth-service
      - routing-service
      - message-service
      - usermanagement-service

  mongo:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-gethome}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  prometheus-data:
  grafana-data:
  alertmanager-data: