name: EC2 Ansible Docker Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key, run Ansible playbook, and clean up
        run: |
          # Create SSH key file
          mkdir -p infra/ansible
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

          # Create Ansible inventory file
          echo "[ec2]" > inventory
          echo "${{ secrets.PUBLIC_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=infra/ansible/key.pem ansible_python_interpreter=/usr/bin/python3" >> inventory

          echo "=== Inventory content ==="
          cat inventory

          # Run the playbook
          cd infra/ansible
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ../../inventory playbook.yml

          # Clean up SSH key file
          rm -f key.pem
