name: EC2 Ansible Docker Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PUBLIC_DNS: ec2-54-227-141-25.compute-1.amazonaws.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Create Ansible inventory
        run: |
          echo "[ec2]" > inventory
          echo "${{ env.PUBLIC_DNS }} ansible_user=ubuntu ansible_ssh_private_key_file=./key.pem ansible_python_interpreter=/usr/bin/python3" >> inventory

      - name: Show inventory (debug)
        run: cat inventory

      - name: Run Ansible Playbook
        run: |
          cd infra/ansible
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ../../inventory playbook.yml
