name: EC2 Ansible Docker Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key, run Ansible playbook, and clean up
        env:
          # Pass GitHub secrets as environment variables to Ansible
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MONGO_ROOT_PASSWORD: ${{ secrets.MONGO_ROOT_PASSWORD }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TWILIO_PHONE_NUMBER: ${{ secrets.TWILIO_PHONE_NUMBER }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENROUTE_API_KEY: ${{ secrets.OPENROUTE_API_KEY }}
        run: |
          # Create directory and write private key file
          mkdir -p infra/ansible
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > infra/ansible/key.pem
          chmod 600 infra/ansible/key.pem

          # Create Ansible inventory with relative key path (key.pem)
          echo "[ec2]" > inventory
          echo "${{ secrets.PUBLIC_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=key.pem ansible_python_interpreter=/usr/bin/python3" >> inventory

          echo "=== Inventory content ==="
          cat inventory

          # Change to ansible directory and run playbook, disable host key checking
          cd infra/ansible
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i ../../inventory playbook.yml

          # Remove private key file after running
          rm -f key.pem
