name: EC2 Ansible Docker Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Create Ansible inventory
        run: |
          echo "[ec2]" > inventory
          echo "$PUBLIC_IP ansible_user=ec2-user ansible_ssh_private_key_file=./key.pem" >> inventory

      - name: Run Ansible Playbook
        run: |
          cd infra/ansible
          ansible-playbook -i ../../inventory playbook.yml
