name: Quick Test

on:
  push:
    branches-ignore: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  quick-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: client/package-lock.json

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Quick Java tests
      run: |
        for service in auth-service usermanagement-service message-service routing-service; do
          echo "Testing $service..."
          cd server/$service
          chmod +x ./gradlew
          ./gradlew test --no-daemon --continue || echo "Tests failed for $service"
          cd ../..
        done

    - name: Quick React tests
      run: |
        cd client
        npm ci
        npm test -- --watchAll=false --passWithNoTests || echo "React tests failed"

    - name: Quick Python tests
      run: |
        cd server/ai-service
        pip install -r requirements.txt
        python -m pytest tests/ -v --tb=short || echo "AI service tests failed"



    - name: Test summary
      run: |
        echo "Quick test completed!"
        echo "Check the logs above for any failures." 